#!/usr/bin/python

import random
from subprocess import call

song_nr = random.randint(0, 200)

url = "https://www.youtube.com/embed/videoseries?list=PLN_pi2niJPgS1uK9K1zmzpw0z8aFhBpn0&index={}&autoplay=1".format(song_nr)


call(["firefox", url])

